# Generated by Django 3.1.4 on 2024-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
