# Generated by Django 3.1.4 on 2024-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='year_of_filling',
            field=models.IntegerField(null=True),
        ),
    ]
