# Generated by Django 3.1.4 on 2024-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='p9_file_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
