# Generated by Django 3.1.4 on 2024-05-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20240525_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='session_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
            preserve_default=False,
        ),
    ]
