# Generated by Django 3.1.4 on 2024-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_p9_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='year_of_filling',
        ),
        migrations.AddField(
            model_name='job',
            name='date_to_file',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
