# Generated by Django 3.1.4 on 2024-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='channel_id',
            field=models.CharField(max_length=255),
        ),
    ]
