# Generated by Django 3.1.4 on 2024-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_has_tax_obligations'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_filed',
            field=models.BooleanField(default=False),
        ),
    ]
