# Generated by Django 3.1.4 on 2024-05-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20240525_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='step',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open'), ('In_Progress', 'In_Progress')], default='START', max_length=20),
        ),
    ]
