# Generated by Django 3.1.4 on 2024-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='session_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
