# Generated by Django 3.1.4 on 2024-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_is_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='nhif_contributions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pension_contributions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
