# Generated by Django 3.1.4 on 2024-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20240526_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='session_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='step',
            field=models.CharField(default='START', max_length=50),
        ),
    ]
