# Generated by Django 3.1.4 on 2024-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20240526_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='nhif_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
