# Generated by Django 3.1.4 on 2024-06-11 20:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_nhif_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tax_document_extracted_info',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
