# Generated by Django 3.1.4 on 2024-06-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_tax_document_extracted_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
