# Generated by Django 3.1.4 on 2024-06-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20240612_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='payment_amount',
            new_name='expected_payment_amount',
        ),
        migrations.AddField(
            model_name='job',
            name='mpesa_paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='mpesa_reference',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
