# Generated by Django 3.1.4 on 2024-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20240613_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_option',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
