# Generated by Django 3.1.4 on 2024-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_output_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='screenshot_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
