# Generated by Django 3.1.4 on 2024-06-16 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_file_nil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='channel_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
