# Generated by Django 3.1.4 on 2024-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
