# Generated by Django 3.1.4 on 2024-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20240617_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='manual_filing',
            field=models.BooleanField(default=False),
        ),
    ]
